[[redirects]]
  from = "/steam-api/*"
  to = "https://api.steampowered.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/steam-usercontent/*"
  to = "https://*.steamusercontent.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bga-proxy/*"
  to = "https://en.boardgamearena.com/:splat"
  status = 200
  force = true

[[edge_functions]]
  function = "og-image"
  path = "/"

[[edge_functions]]
  function = "og-image"
  path = "/index.html"
